config/routes.rb
Rails.application.routes.draw do
  get '/oauth/callback', to: 'oauth#callback'
  post '/photos/:id/tweet', to: 'photos#tweet', as: 'tweet_photo'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :photos, only: [:new, :create, :show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :image, presence: true
  validates :description, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  private

  def require_login
    if current_user.nil?
      flash[:error] = ["You must be logged in to access this section"]
      redirect_to root_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
  end
end

app/controllers/oauth_controller.rb
require 'net/http'
require 'json'

class OauthController < ApplicationController
  def callback
    if params[:code].present?
      token_params = {
        code: params[:code],
        client_id: Rails.application.credentials.client_id,
        client_secret: Rails.application.credentials.client_secret,
        redirect_uri: "http://localhost:3000/oauth/callback",
        grant_type: "authorization_code"
      }
      token_uri = URI("http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/token")
      token_response = Net::HTTP.post_form(token_uri, token_params)

      if token_response.is_a?(Net::HTTPSuccess)
        token_data = JSON.parse(token_response.body)
        session[:access_token] = token_data["access_token"]

        redirect_to root_path
      else
        flash[:error] = "Failed to obtain access token."
        redirect_to root_path
      end
    else
      flash[:error] = "Authorization code not found."
      redirect_to root_path
    end
  end
end

app/controllers/photos_controller.rb
require 'net/http'
require 'uri'
require 'json'

class PhotosController < ApplicationController
  def new
    @photo = current_user.photos.new
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def create
    errors = []
    if params[:photo][:image].nil?
      errors << "Image file was not entered"
    end
    if params[:photo][:description].empty?
      errors << "Title was not entered"
    end
    if params[:photo][:description].length >= 30
      errors << "Title it too long(maximum 30 characters)"
    end
    @photo = current_user.photos.new(photo_params)

    if errors.any?
      flash[:error] = errors
      redirect_to new_photo_path
    elsif @photo.save
      redirect_to root_path, notice: 'Photo uploaded successfully!'
    else
      render :new, alert: 'Failed to upload photo.'
    end
  end

  def tweet
    unless session[:access_token].present?
      flash[:error] = "Access token not found. Please link with Twitter."
      redirect_to root_path and return
    end

    @photo = Photo.find(params[:id])

    tweet_data = {
      text: @photo.description,
      url: photo_url(@photo)
    }
    tweet_api_uri = URI("http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/api/tweets")
    headers = {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{session[:access_token]}"
    }
    http = Net::HTTP.new(tweet_api_uri.host, tweet_api_uri.port)
    request = Net::HTTP::Post.new(tweet_api_uri.path, headers)
    request.body = tweet_data.to_json

    response = http.request(request)

    if response.code == "201"
      flash[:success] = "Tweet posted successfully!"
    else
      flash[:error] = "Failed to post tweet. Error code: #{response.code}"
    end

    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :description)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    errors = []
    if params[:user][:id].empty?
      errors << "Please enter User ID"
    end
    if params[:user][:password].empty?
      errors << "Please enter Password"
    end

    @user = User.find_by(id: params[:user][:id])

    if errors.any?
      flash[:error] = errors
      redirect_to new_user_session_path
    elsif @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = ["User ID or Password wrong"]
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoManager</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div id="flash-messages" style="max-width:600px">
  <% flash.each do |type, messages| %>
    <% if messages.is_a?(String) %>
      <% messages = [messages] %>
    <% end %>
    <% messages.each do |message| %>
      <label>
        <input type="checkbox" class="alertCheckbox" autocomplete="off"/>
        <div class="alert <%= type %>">
          <span class="alertClose">X</span>
          <span class="alertText"><%= message %>
            <br class="clear"/></span>
        </div>
      </label>
    <% end %>
  <% end %>
</div>
<%= yield %>
</body>
</html>

app/views/main/index.html.erb
<% if current_user %>
  <h1>Welcome, <%= current_user.id %></h1>
  <%= link_to 'Link with Twitter',
              "http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/authorize" +
                "?client_id=#{Rails.application.credentials.client_id}&response_type=code&redirect_uri=http://localhost:3000/oauth/callback&scope=write_tweet"
  %>  <br>

  <%= link_to 'Log out', user_session_path(current_user), data: { turbo_method: :delete } %><br>
  <%= link_to 'new photo', new_photo_path(current_user) %><br>
  <div class="container">
    <% current_user.photos.order("created_at desc").each_slice(7) do |slice| %>
      <div class="row">
        <% slice.each do |photo| %>
          <div class="image-block">
            <p class="image-text"><%= photo.description %></p>
            <%= image_tag photo.image, size: '200' %>
            <%= link_to 'Tweet', tweet_photo_path(photo), data: { turbo_method: :post } %><br>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <h1>This is the index page</h1>
  <%= link_to 'Login', new_user_session_path %><br>
<% end %>

app/views/photos/new.html.erb
<h1>Upload a Photo</h1>
<%= form_with(model: @photo, url: photos_path, local: true) do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %><br>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit 'Upload' %>
<% end %>
<%= link_to 'Back', root_path %><br>
<%= link_to 'Log out', user_session_path(current_user), data: { turbo_method: :delete } %>

app/views/photos/show.html.erb
<div>
  <%= image_tag @photo.image %>
  <p><%= @photo.description %></p>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login page</h1>
<%= form_with model: @user, url: user_sessions_path do |f| %>
  <div>
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>